version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: passwordmanager-api
    restart: always
    network_mode: "host"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./appsettings.Production.json:/app/appsettings.Production.json:ro